title: KindaMadLad blog
email: temptaki5002@example.com
description: >- 
  Just doing the same thing over and over and over
url: https://KindaMadLad-blog 
baseurl: /KindaMadLad-blog
github_username:  t-88

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
